pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases" }
    }
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '2.0.21'
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
    versionCatalogs {
        forge {
            from(files("gradle/forge.versions.toml"))
        }
    }
}

include ':modularui'
project(':modularui').projectDir = file('modularui')

rootProject.name = "${mod_id}"
