[versions]
registrate = "MC26.1-1.5.0"
configuration = "4.1.2+26.1.2"
jei = "29.35.0.94"
rei = "26.1.819"
emi = "1.1.24+1.20.1"
ae2 = "26.1.11-beta"
kubejs = "26.1.2-8.0.4"
rhino = "2101.2.8-build.91"
architectury = "20.0.12"
clothmath = "0.6.1"
clothconfig = "26.1.154"
curios = "15.0.0+26.1.2"
kotlinforforge = "6.3.0"
journeyMapApi = "2.0.0-26.1-SNAPSHOT"
ftblibrary = "26.1.2.7"
ftbteams = "26.1.2.4"
ftbquests = "26.1.2.7"
ftbchunks = "26.1.2.8"
ccTweaked = "1.120.0"
create = "6.0.6-150"
ponder = "1.0.80"
flywheel = "1.0.4"
xaerosLib = "1.1.0"
xaerosWorldMap = "1.45.0"
xaerosMinimap = "26.4.2"

## modrinth maven ##
jade = "26.1.10+neoforge"
embeddium = "0.3.31-beta.53+mc1.20.1"
oculus = "1.20.1-1.8.0"
modernfix = "5.27.22+mc26.1.2"

## cursemaven ##
worldStripper = "4578579"
javd = "7869081"
trenzalore = "7957903"
journeyMap = "8768945"
resourcefullib = "4.0.1"
argonauts = "5263580"
heracles = "5406935"
ae2wtlib = "26.1.1-beta"
spark = "8275631"
observable = "5643037"
gamestages = "15.0.2"
bookshelf = "8551659"

[libraries]
registrate          = { module = "com.tterrag.registrate:Registrate", version.ref = "registrate" }
configuration       = { module = "dev.toma.configuration:configuration-neoforge", version.ref = "configuration" }
jei-common-api      = { module = "mezz.jei:jei-26.1.2-common-api", version.ref = "jei" }
jei-forge-api       = { module = "mezz.jei:jei-26.1.2-neoforge-api", version.ref = "jei" }
jei-forge-impl      = { module = "mezz.jei:jei-26.1.2-neoforge", version.ref = "jei" }
rei-plugin          = { module = "me.shedaniel:RoughlyEnoughItems-default-plugin", version.ref = "rei" }
rei-api             = { module = "me.shedaniel:RoughlyEnoughItems-api-neoforge", version.ref = "rei" }
rei-forge           = { module = "me.shedaniel:RoughlyEnoughItems-neoforge", version.ref = "rei" }
emi                 = { module = "dev.emi:emi-forge", version.ref = "emi" }

ae2                 = { module = "org.appliedenergistics:appliedenergistics2", version.ref = "ae2" }
create              = { module = "com.simibubi.create:create-1.20.1", version.ref = "create"}
ponder              = { module = "net.createmod.ponder:Ponder-Forge-1.20.1", version.ref = "ponder"}
flywheel-forge-api  = { module = "dev.engine-room.flywheel:flywheel-forge-api-1.20.1", version.ref = "flywheel"}
flywheel-forge      = { module = "dev.engine-room.flywheel:flywheel-forge-1.20.1", version.ref = "flywheel"}
kubejs              = { module = "dev.latvian.mods:kubejs-neoforge", version.ref = "kubejs" }
rhino               = { module = "dev.latvian.mods:rhino", version.ref = "rhino" }
architectury        = { module = "dev.architectury:architectury-neoforge", version.ref = "architectury" }
clothmath           = { module = "me.shedaniel.cloth:basic-math", version.ref = "clothmath" }
clothconfig         = { module = "me.shedaniel.cloth:cloth-config-neoforge", version.ref = "clothconfig" }
curios              = { module = "top.theillusivec4.curios:curios-neoforge", version.ref = "curios" }
kotlinforforge      = { module = "thedarkcolour:kotlinforforge-neoforge", version.ref = "kotlinforforge" }
journeymap-api      = { module = "info.journeymap:journeymap-api-neoforge", version.ref = "journeyMapApi" }
ftblibrary          = { module = "dev.ftb.mods:ftb-library-neoforge", version.ref = "ftblibrary" }
ftbteams            = { module = "dev.ftb.mods:ftb-teams-neoforge", version.ref = "ftbteams" }
ftbquests           = { module = "dev.ftb.mods:ftb-quests-neoforge", version.ref = "ftbquests" }
ftbchunks           = { module = "dev.ftb.mods:ftb-chunks-neoforge", version.ref = "ftbchunks" }
jade                = { module = "maven.modrinth:jade", version.ref = "jade" }
embeddium           = { module = "org.embeddedt:embeddium-1.20.1", version.ref = "embeddium" }
oculus              = { module = "maven.modrinth:oculus", version.ref = "oculus" }
modernfix           = { module = "maven.modrinth:modernfix", version.ref = "modernfix" }
xaeroslib           = { module = "xaero.lib:xaerolib-neoforge-26.1.2", version.ref = "xaerosLib" }
xaerosworldmap      = { module = "xaero.map:xaeroworldmap-neoforge-26.1.2", version.ref = "xaerosWorldMap" }
xaerosminimap       = { module = "xaero.minimap:xaerominimap-neoforge-26.1.2", version.ref = "xaerosMinimap" }


cc-tweaked-core-api   = { module = "cc.tweaked:cc-tweaked-26.1.2-common-api", version.ref = "ccTweaked" }
cc-tweaked-forge-api  = { module = "cc.tweaked:cc-tweaked-26.1.2-forge-api", version.ref = "ccTweaked" }
cc-tweaked-forge-impl = { module = "cc.tweaked:cc-tweaked-26.1.2-forge", version.ref = "ccTweaked" }

worldstripper       = { module = "curse.maven:worldStripper-250603", version.ref = "worldStripper" }
javd                = { module = "curse.maven:javd-370890", version.ref = "javd" }
trenzalore          = { module = "curse.maven:trenzalore-870210", version.ref = "trenzalore" }
journeymap-forge    = { module = "curse.maven:journeymap-32274", version.ref = "journeyMap" }
resourcefullib      = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-26.1", version.ref = "resourcefullib" }
argonauts           = { module = "curse.maven:argonauts-845833", version.ref = "argonauts" }
heracles            = { module = "curse.maven:heracles-845831", version.ref = "heracles" }
ae2wtlib            = { module = "de.mari_023:ae2wtlib_api", version.ref = "ae2wtlib" }
spark               = { module = "curse.maven:spark-361579", version.ref = "spark" }
observable          = { module = "curse.maven:observable-509575", version.ref = "observable" }
gamestages          = { module = "net.darkhax.gamestages:GameStages-Forge-1.20.1", version.ref = "gamestages" }
bookshelf           = { module = "curse.maven:bookshelf-228525", version.ref = "bookshelf" }

[bundles]
jei = ["jei-common-api", "jei-forge-api", "jei-forge-impl"]
rei = ["rei-plugin", "rei-forge", "clothmath"]
rei-runtime = ["rei-forge", "architectury", "clothconfig"]
kjs = ["kubejs", "rhino", "architectury"]

